### ISSUE TITLE
Remove the needs review check

### ISSUE THREAD

**Issue by MrPowers** [unitycatalog/unitycatalog#193]
This fails every time I create a PR, can we just remove it?  I am getting lots of emails because of this failing check.

PRs will be checked before they're merged.

<img width="564" alt="Screenshot 2024-07-10 at 10 38 28 AM" src="https://github.com/unitycatalog/unitycatalog/assets/2722395/61968285-1d1d-4a38-89c4-ef3515a725df">

**Comment by asingamaneni** [comment]
Instead of removing completely, can we try using [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)

The job's are failing whenever an issue or pr is created because the token `PROJECT_BOARD_AUTOMATION_TOKEN ` might not be setup in this repository secrets, which is used in both the below files 

https://github.com/unitycatalog/unitycatalog/blob/6e07f9e4e55ba9f8e9c50b2b10c980756fe80026/.github/workflows/project-board-automation-for-issues.yml#L18
https://github.com/unitycatalog/unitycatalog/blob/6e07f9e4e55ba9f8e9c50b2b10c980756fe80026/.github/workflows/project-board-automation-for-prs.yml#L22

Instead of `PROJECT_BOARD_AUTOMATION_TOKEN `, `GITHUB_TOKEN` might work!
